name: Build, test, and deploy push to main

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Run unit/component tests
        run: npm test -- --coverage --passWithNoTests
      - name: Report code coverage
        uses: romeovs/lcov-reporter-action@v0.2.16
        with:
          lcov-file: ./coverage/lcov.info
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create .env.production file
        run: |
          touch .env.production
          echo AUTH0_CLIENT_SECRET=${{ secrets.AUTH0_CLIENT_SECRET }} >> .env.production
          echo NEXT_PUBLIC_AUTH0_CLIENT_ID=${{ secrets.NEXT_PUBLIC_AUTH0_CLIENT_ID }} >> .env.production
          echo NEXT_PUBLIC_AUTH0_DOMAIN=${{ secrets.NEXT_PUBLIC_AUTH0_DOMAIN }} >> .env.production
          echo NEXT_PUBLIC_AUTH0_SCOPE=${{ secrets.NEXT_PUBLIC_AUTH0_SCOPE }} >> .env.production
          echo NEXT_PUBLIC_BASE_URL=${{ secrets.NEXT_PUBLIC_BASE_URL }} >> .env.production
          echo NEXT_PUBLIC_POST_LOGOUT_REDIRECT_URI=${{ secrets.NEXT_PUBLIC_POST_LOGOUT_REDIRECT_URI }} >> .env.production
          echo NEXT_PUBLIC_REDIRECT_URI=${{ secrets.NEXT_PUBLIC_REDIRECT_URI }} >> .env.production
          echo SESSION_COOKIE_LIFETIME=${{ secrets.SESSION_COOKIE_LIFETIME }} >> .env.production
          echo SESSION_COOKIE_SECRET=${{ secrets.SESSION_COOKIE_SECRET }} >> .env.production
      - name: Build and run E2E tests
        uses: cypress-io/github-action@v4
        with:
          browser: chrome
          build: npm run build
          start: npm start
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-args: '--prod'
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}}
