name: Build, test, and deploy push and PRs to main

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Run unit/component tests
        run: npm test -- --coverage --passWithNoTests
      - name: Report code coverage
        uses: romeovs/lcov-reporter-action@v0.2.16
        with:
          lcov-file: ./coverage/lcov.info
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create .env file
        run: |
          touch .env
          echo AUTH0_ISSUER_BASE_URL=${{ secrets.AUTH0_ISSUER_BASE_URL }} >> .env
          echo AUTH0_CLIENT_ID=${{ secrets.AUTH0_CLIENT_ID }} >> .env
          echo AUTH0_CLIENT_SECRET=${{ secrets.AUTH0_CLIENT_SECRET }} >> .env
          echo NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }} >> .env
          echo NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }} >> .env
      - name: Create cypress.env.json file
        id: create-json
        uses: jsdaniell/create-json@1.1.2
        with:
          name: 'cypress.env.json'
          json: ${{ secrets.CYPRESS_ENV_JSON }}
      - name: Build and run E2E tests
        uses: cypress-io/github-action@v4
        with:
          browser: chrome
          build: npm run build
          start: npm start
